return{
        "akinsho/toggleterm.nvim",
        version="*",
        opts={
                size=15,
                open_mapping=[[<C-\>]],
                direction="float",
                shade_terminals=true,
                float_opts={
                        border="curved",
                },
        },
}
